### ISSUE TITLE
Error while trying to run mix test

### ISSUE THREAD

**Issue by InverMN** [YgorCastor/ravix-ecto#1]
Hello,

I am tryin' to run `mix test` while using RavenDB while using this driver, but I get `** (Mix) Expected Ravix.Ecto.Adapter to implement Ecto.Adapter.Storage in order to create storage for MesStore.Repo`. That's kinda interesting because `mix phx.server` runs perfectly as database and repo work. 

Is it yet not implemented feature or I did miss something?

**Comment by ycastorium** [comment]
Ahh, i did not implemented the Storage behaviour yet, i'll do that in a bit and release a version.

**Comment by InverMN** [comment]
Okay, waiting for it 😊

**Comment by ycastorium** [comment]
Fixed on [v0.2.1](https://github.com/YgorCastor/ravix-ecto/releases/tag/v0.2.1)

I've created a small sample with working configuration and some caveats explanations

https://github.com/YgorCastor/phoenix-ravix-sample
