### ISSUE TITLE
Loading of types :decimal and :time

### ISSUE THREAD

**Issue by InverMN** [YgorCastor/ravix-ecto#8]
Issue was firstly posted here: https://elixirforum.com/t/ecto-time-and-decimal-types-throw-error-on-load-from-database/49494

Is there really lack of support for these types?

**Comment by ycastorium** [comment]
Thanks for the report, i missed those, fixed in version https://github.com/YgorCastor/ravix-ecto/releases/tag/v0.3.2

**Comment by InverMN** [comment]
When I updated Ravix-Ecto, I started getting this error while compiling:
```
== Compilation error in file lib/ravix_ecto/parsers/query_parser.ex ==
** (CompileError) lib/ravix_ecto/parsers/query_parser.ex:386: Ravix.RQL.Tokens.Order.Field.__struct__/1 is undefined, cannot expand struct Ravix.RQL.Tokens.Order.Field. Make sure the struct name is correct. If the struct name exists and is correct but it still cannot be found, you likely have cyclic module usage in your code
    lib/ravix_ecto/parsers/query_parser.ex:383: (module)
could not compile dependency :ravix_ecto, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile ravix_ecto", update it with "mix deps.update ravix_ecto" or clean it with "mix deps.clean ravix_ecto"
```

**Comment by ycastorium** [comment]
> When I updated Ravix-Ecto, I started getting this error while compiling:
> 
> ```
> == Compilation error in file lib/ravix_ecto/parsers/query_parser.ex ==
> ** (CompileError) lib/ravix_ecto/parsers/query_parser.ex:386: Ravix.RQL.Tokens.Order.Field.__struct__/1 is undefined, cannot expand struct Ravix.RQL.Tokens.Order.Field. Make sure the struct name is correct. If the struct name exists and is correct but it still cannot be found, you likely have cyclic module usage in your code
>     lib/ravix_ecto/parsers/query_parser.ex:383: (module)
> could not compile dependency :ravix_ecto, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile ravix_ecto", update it with "mix deps.update ravix_ecto" or clean it with "mix deps.clean ravix_ecto"
> ```

Can you do a mix deps.clean and mix deps.update --all? It can be a mismatch or corrupted dependency. I'm using the same version right now/

**Comment by InverMN** [comment]
Okay, I found the problem. I was using outdated version of Ravix. For future I should look at package versions on hex.pm instead Github releases. Anyway big thanks for help!
